Name:           ros-hydro-moveit-core
Version:        0.5.11
Release:        0%{?dist}
Summary:        ROS moveit_core package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       boost-devel
Requires:       eigen3-devel
Requires:       ros-hydro-actionlib-msgs
Requires:       ros-hydro-console-bridge
Requires:       ros-hydro-eigen-conversions
Requires:       ros-hydro-eigen-stl-containers
Requires:       ros-hydro-fcl
Requires:       ros-hydro-geometric-shapes >= 0.3.4
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-kdl-parser
Requires:       ros-hydro-moveit-msgs
Requires:       ros-hydro-octomap
Requires:       ros-hydro-octomap-msgs
Requires:       ros-hydro-random-numbers
Requires:       ros-hydro-rostime
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-shape-msgs
Requires:       ros-hydro-shape-tools
Requires:       ros-hydro-srdfdom
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-trajectory-msgs
Requires:       ros-hydro-urdfdom
Requires:       ros-hydro-urdfdom-headers
Requires:       ros-hydro-visualization-msgs
BuildRequires:  assimp
BuildRequires:  boost-devel
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-hydro-actionlib-msgs
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-console-bridge
BuildRequires:  ros-hydro-eigen-conversions
BuildRequires:  ros-hydro-eigen-stl-containers
BuildRequires:  ros-hydro-fcl
BuildRequires:  ros-hydro-geometric-shapes >= 0.3.4
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-kdl-parser
BuildRequires:  ros-hydro-moveit-msgs
BuildRequires:  ros-hydro-moveit-resources
BuildRequires:  ros-hydro-octomap
BuildRequires:  ros-hydro-octomap-msgs
BuildRequires:  ros-hydro-orocos-kdl
BuildRequires:  ros-hydro-random-numbers
BuildRequires:  ros-hydro-roslib
BuildRequires:  ros-hydro-rostime
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-shape-msgs
BuildRequires:  ros-hydro-shape-tools
BuildRequires:  ros-hydro-srdfdom
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf-conversions
BuildRequires:  ros-hydro-trajectory-msgs
BuildRequires:  ros-hydro-urdfdom
BuildRequires:  ros-hydro-urdfdom-headers
BuildRequires:  ros-hydro-visualization-msgs

%description
Core libraries used by MoveIt!

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Jan 21 2015 Sachin Chitta <robot.moveit@gmail.com> - 0.5.11-0
- Autogenerated by Bloom

* Tue Dec 09 2014 Sachin Chitta <robot.moveit@gmail.com> - 0.5.10-0
- Autogenerated by Bloom

